seed: 0
output_dir: ./st_mem
exp_name: pretrain
resume: null
start_epoch: 0
model_name: st_mem_vit_base_dec256d4b
device: cuda
batch_size: 16

ddp:
  world_size: 1
  rank: -1
  gpu: 0
  dist_url: env://
  dist_backend: nccl
  distributed: false

model:
  seq_len: 2500
  patch_size: 100
  num_leads: 3
  norm_pix_loss: true

dataset:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  lead: 12lead
  fs: 250
  index_dir: ./data/dummy
  ecg_dir: ./data/dummy/ecgs

  train_csv: index.csv

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataloader:
  batch_size: 16
  num_workers: 8
  pin_memory: True

train:
  epochs: 100
  accum_iter: 1
  warmup_epochs: 3
  val_interval: 2
  min_lr: 0
  blr: 1.6e-4
  lr: 1.0e-4
  weight_decay: 0.01
  optimizer: adamw
  optimizer_kwargs:
    betas: [0.9, 0.95]
