seed: 0
output_dir: ./st_mem
resume: null
start_epoch: 0
encoder_path: ./st_mem/pretrain/encoder.pth
model_name: st_mem_vit_base
mode: finetune
device: cuda:0
batch_size: 1
task: ref
flag: train
dataset: PTB_XL

root_path: null
data_path: null
embedding_path: null
ref_path: null

ddp:
  world_size: 1
  rank: -1
  gpu: 0
  dist_url: env://
  dist_backend: nccl
  distributed: false

model:
  seq_len: 2500
  patch_size: 100
  num_leads: 3
  num_classes: null

loss:
  name: cross_entropy

metric:
  task: multiclass
  compute_on_cpu: true
  sync_on_compute: false
  num_classes: 3
  target_metrics:
  - Accuracy
  - F1Score:
      average: macro
  - AUROC:
      average: macro
